name: react-app

on:
  pull_request:
    branches:
    - master

jobs:
  react-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: |
          npm install
          npm i prettier
          npm run lint
          npm run prettier
          CI=true npm run test
          npm run build